# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef1e1223b3ddc025be950cffb878336207ccb34626e0a50f7f62ecf45c7536c16af39eef5085117aac871a4159f08bbb68f9cac029475d0280941509204db4dc

test:
  secret_key_base: 2e12e926a9ca8fb7401717de84b26e73896456d97570088bd14ead82a0447b1c8e2c19ead12240be4dd34d9ce5ec2f33a7ffe4bd8103b0ae82aa14e8b9b664e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
